version: '3.8'

services:
  medflow-ai:
    build:
      context: ./medflow-ai
      dockerfile: Dockerfile
    container_name: medflow-ai
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      - GRPC_HOST=0.0.0.0
    # Cấu hình tự động restart khi sập
    restart: unless-stopped

  medflow-server:
    build:
      context: ./medflow-server
      dockerfile: Dockerfile
    container_name: medflow-server
    ports:
      - "4000:4000"
    environment:
      # Lấy trực tiếp từ file .env trong host hoặc định nghĩa tại đây
      - DATABASE_URL=${DATABASE_URL}
      - AWS_REGION=${AWS_REGION}
      - COGNITO_USER_POOL_ID=${COGNITO_USER_POOL_ID}
      - COGNITO_CLIENT_ID=${COGNITO_CLIENT_ID}
      - COGNITO_CLIENT_SECRET=${COGNITO_CLIENT_SECRET}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
    env_file:
      - ./medflow-server/.env
    restart: unless-stopped
    depends_on:
      - medflow-ai

  medflow-client:
    build:
      context: ./medflow-client
      dockerfile: Dockerfile
    container_name: medflow-client
    ports:
      - "3000:3000"
    environment:
      # Nếu client cần env
      - NODE_ENV=production
    restart: unless-stopped
    depends_on:
      - medflow-server
